const Ziggy = {"url":"http:\/\/localhost\/mediceram\/public","port":null,"defaults":{},"routes":{"dashboard":{"uri":"dashboard","methods":["GET","HEAD"]},"beacons":{"uri":"beacons","methods":["GET","HEAD"]},"beacons-store":{"uri":"beacons-store","methods":["POST"],"bindings":{"beacon":"id"}},"beacons-update":{"uri":"beacons-update","methods":["POST"]},"beacons-delete":{"uri":"beacons-delete","methods":["POST"]},"workers":{"uri":"workers","methods":["GET","HEAD"]},"workers-store":{"uri":"workers-store","methods":["POST"],"bindings":{"worker":"id"}},"workers-update":{"uri":"workers-update","methods":["POST"]},"workers-delete":{"uri":"workers-delete","methods":["POST"]},"get-avail-beacons":{"uri":"get-avail-beacons","methods":["GET","HEAD"]},"customers":{"uri":"customers","methods":["GET","HEAD"]},"customers-store":{"uri":"customers-store","methods":["POST"],"bindings":{"customers":"id"}},"customers-update":{"uri":"customers-update","methods":["POST"]},"customers-delete":{"uri":"customers-delete","methods":["POST"]},"mould-models":{"uri":"mould-models","methods":["GET","HEAD"]},"mould-models-store":{"uri":"mould-models-store","methods":["POST"],"bindings":{"mould_model":"id"}},"mould-models-update":{"uri":"mould-models-update","methods":["POST"]},"mould-models-delete":{"uri":"mould-models-delete","methods":["POST"]},"orders":{"uri":"orders","methods":["GET","HEAD"]},"orders-store":{"uri":"orders-store","methods":["POST"],"bindings":{"order":"id"}},"orders-update":{"uri":"orders-update","methods":["POST"]},"orders-delete":{"uri":"orders-delete","methods":["POST"]},"orders-complete":{"uri":"orders-complete","methods":["POST"]},"orders-export":{"uri":"orders-export\/{id}","methods":["GET","HEAD"]},"orders-monitor":{"uri":"orders-monitor","methods":["GET","HEAD"]},"orders-monitor-view-station":{"uri":"orders-monitor-view-station\/{id}","methods":["GET","HEAD"]},"former-data":{"uri":"get-former-data\/{id}","methods":["GET","HEAD"]},"former-data-table":{"uri":"get-former-data-table\/{id}","methods":["GET","HEAD"]},"moulds-for-date":{"uri":"get-moulds-for-date","methods":["GET","HEAD"]},"moulds-for-failure_rate":{"uri":"get-moulds-for-failure_rate","methods":["GET","HEAD"]},"register":{"uri":"register","methods":["GET","HEAD"]},"login":{"uri":"login","methods":["GET","HEAD"]},"password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},"password.email":{"uri":"forgot-password","methods":["POST"]},"password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"]},"password.update":{"uri":"reset-password","methods":["POST"]},"verification.notice":{"uri":"verify-email","methods":["GET","HEAD"]},"verification.verify":{"uri":"verify-email\/{id}\/{hash}","methods":["GET","HEAD"]},"verification.send":{"uri":"email\/verification-notification","methods":["POST"]},"password.confirm":{"uri":"confirm-password","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
